version: '3'
services:
  config-service:
    build: config-service
    image: config-service
    restart: unless-stopped
    ports:
      - 8888:8888
    environment:
      JAVA_OPTS: >
        -Dspring.profiles.active=native

  discovery-service:
    build: discovery-service
    image: discovery-service
    restart: unless-stopped
    ports:
      - 8761:8761
    environment:
      JAVA_OPTS: >
        -Dspring.cloud.config.uri=http://config-service:8888